projects:
  - 'projects/**'
ci_workflows:
  - '.github/workflows/build-projects.yaml'
generic_drivers:
  - 'drivers/**'
  - '!drivers/platform/**'
platform_maxim:
  - 'drivers/platform/maxim/**'
platform_pico:
  - 'drivers/platform/pico/**'
platform_mbed:
  - 'drivers/platform/mbed/**'
platform_stm32:
  - 'drivers/platform/stm32/**'
platform_xilinx:
  - 'drivers/platform/xilinx/**'
platform_altera:
  - 'drivers/platform/altera/**'
platform_aducm3029:
  - 'drivers/platform/aducm3029/**'
platform_chibios:
  - 'drivers/platform/chibios/**'
platform_freeRTOS:
  - 'drivers/platform/freeRTOS/**'
platform_ftd2xx:
  - 'drivers/platform/ftd2xx/**'
platform_generic:
  - 'drivers/platform/generic/**'
platform_linux:
  - 'drivers/platform/linux/**'
platform_mac:
  - 'drivers/platform/mac/**'
platform_win:
  - 'drivers/platform/win/**'